### ISSUE TITLE
JSON.parse error in Docker

### ISSUE THREAD

**Issue by jlaamanen** [jlaamanen/signally#2]
When started in Docker, events sent with CLI fail in parsing from JSON:

```
Error when handling event 1: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.readJsonFile (/app/node_modules/signally/dist/utils.js:26:17)
    at FSWatcher.<anonymous> (/app/node_modules/signally/dist/listener.js:28:34)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1364:12)
```

Manually entering events to `.signally` inside the container is working fine:

```sh
echo '{"event": "hello", "messages": ["Hei"]}' > .signally/1
```

**Comment by jlaamanen** [comment]
It seems that inside containers fs.watch works a bit differently: normally new file would only trigger 1 watch event (`rename`) with the contents being immediately accessible, but inside a container there would be 2 events (`rename` and `change`), and the contents are filled in the `change` event.

Should be fixed by implementing logic for checking that file contents isn't empty before trying to parse it as JSON.
